/**
 * Imports the legacy NPG (CodeIgniter / MySQL) farm database into Farmora
 * under a dedicated manager account.
 *
 * Reads scripts/npg/npg-data.json (generated by export-data.js) unless
 * --data points elsewhere.
 *
 *   bun scripts/npg/import.js [--username npg] [--name "NPG Farm"]
 *                             [--package Premium] [--months 12] [--password <pw>]
 *   bun scripts/npg/import.js --replace                   # re-import (cutover)
 *   bun scripts/npg/import.js --remove [--username npg]   # delete the tenant
 *
 * --replace wipes every business record of the tenant and imports the data
 * again, keeping the manager, subscription and staff logins.
 */
import { parseArgs } from 'node:util'
import bcrypt from 'bcryptjs'
import { QueryTypes } from 'sequelize'
import { sequelize } from '@utils/db'
import { DEFAULT_DATA_FILE, loadLegacyData } from './data-file.js'

const { values: args } = parseArgs({
  options: {
    data: { type: 'string', default: DEFAULT_DATA_FILE },
    username: { type: 'string', default: 'npg' },
    name: { type: 'string', default: 'NPG Farm' },
    package: { type: 'string', default: 'Premium' },
    months: { type: 'string', default: '12' },
    password: { type: 'string' },
    replace: { type: 'boolean', default: false },
    remove: { type: 'boolean', default: false },
  },
})

const LEGACY_ITEM_TYPES = {
  Chick: { type: 'chick', name: 'Chick' },
  chick: { type: 'chick', name: 'Chick' },
  BF: { type: 'FINISHER', name: 'Broiler Finisher (BF)' },
  BS: { type: 'STARTER', name: 'Broiler Starter (BS)' },
  PBS: { type: 'PRE STARTER', name: 'Pre Starter (PBS)' },
  Medicine: { type: 'medicine', name: 'Medicine' },
  others: { type: 'regular', name: 'Others' },
}

const BUSINESS_PLUS_LABELS = {
  rental_farm_cost: 'Rental Farm',
  rental_farm_salary: 'Salary',
  egg_setting_book: 'Egg Setting',
}

const STAFF_EXCLUDED_PERMISSION_PREFIXES = [
  'user:',
  'role:',
  'subscriber:',
  'package:',
  'subscription:',
  'referral:',
  'referral_ledger:',
]

const warnings = []
const warn = (msg) => warnings.push(msg)

const txt = (v) => (v == null ? null : String(v).trim() || null)
const num = (v) => (txt(v) === null ? 0 : Number(v))
const ref = (v) => (txt(v) === null || Number(v) === 0 ? null : Number(v))
const day = (v) => {
  const s = txt(v)
  if (!s || s.startsWith('0000')) return null
  return new Date(`${s.slice(0, 10)}T00:00:00Z`)
}
const legacyTs = (v) => {
  const s = txt(v)
  if (!s || s.startsWith('0000')) return null
  return new Date(`${s.replace(' ', 'T')}Z`)
}
const closeReportDate = (v) => {
  const m = /^(\d{2})-(\d{2})-(\d{4}) (\d{2}):(\d{2}) (AM|PM)$/.exec(
    txt(v) || ''
  )
  if (!m) return null
  const [, d, mo, y, hh, mm, ap] = m
  const hours = (Number(hh) % 12) + (ap === 'PM' ? 12 : 0)
  return new Date(
    `${y}-${mo}-${d}T${String(hours).padStart(2, '0')}:${mm}:00+05:30`
  )
}
const addMonths = (date, months) => {
  const d = new Date(date)
  d.setUTCMonth(d.getUTCMonth() + months)
  return d
}
const round2 = (n) => Math.round(n * 100) / 100
const stamps = (row, now) => ({
  created_at: legacyTs(row?.created_at) ?? now,
  updated_at: legacyTs(row?.updated_at ?? row?.updated_date) ?? now,
})

const qi = sequelize.getQueryInterface()

const select = (sql, replacements, transaction) =>
  sequelize.query(sql, { replacements, transaction, type: QueryTypes.SELECT })

const insertMany = async (table, rows, transaction) => {
  const ids = []
  for (let i = 0; i < rows.length; i += 500) {
    const result = await qi.bulkInsert(table, rows.slice(i, i + 500), {
      transaction,
      returning: ['id'],
    })
    ids.push(...result.map((r) => r.id))
  }
  return ids
}

const insertOne = async (table, row, transaction) =>
  (await insertMany(table, [row], transaction))[0]

const findManager = async (transaction) => {
  const [user] = await select(
    'SELECT id, user_type FROM users WHERE username = :username',
    { username: args.username },
    transaction
  )
  if (user && user.user_type !== 'manager') {
    throw new Error(`User "${args.username}" exists but is not a manager`)
  }
  return user
}

const wipeTenantData = async (masterId, transaction) => {
  const run = (sql) =>
    sequelize.query(sql, { replacements: { masterId }, transaction })
  await run(
    'DELETE FROM purchase_batch_assignments WHERE purchase_id IN (SELECT id FROM purchases WHERE master_id = :masterId)'
  )
  for (const table of [
    'investor_transactions',
    'investor_managements',
    'purchases',
    'purchase_returns',
    'purchase_books',
    'sales',
    'general_expenses',
    'expense_sales',
    'integration_books',
    'working_costs',
    'batches',
    'farms',
    'seasons',
    'items',
    'vendors',
  ]) {
    await run(`DELETE FROM ${table} WHERE master_id = :masterId`)
  }
}

const removeTenant = async () => {
  await sequelize.transaction(async (t) => {
    const manager = await findManager(t)
    if (!manager) throw new Error(`Manager "${args.username}" not found`)
    const run = (sql) =>
      sequelize.query(sql, {
        replacements: { masterId: manager.id },
        transaction: t,
      })

    await wipeTenantData(manager.id, t)
    await run(
      'DELETE FROM user_permissions WHERE user_id IN (SELECT id FROM users WHERE parent_id = :masterId)'
    )
    await run(
      'DELETE FROM user_role_assignments WHERE user_id IN (SELECT id FROM users WHERE parent_id = :masterId)'
    )
    await run(
      "DELETE FROM users WHERE parent_id = :masterId AND user_type = 'staff'"
    )
    await run('DELETE FROM invoice_configs WHERE parent_id = :masterId')
    await run('DELETE FROM payments WHERE user_id = :masterId')
    await run('DELETE FROM subscriptions WHERE user_id = :masterId')
    await run('DELETE FROM users WHERE id = :masterId')
  })
  console.log(`Removed tenant "${args.username}" and all of its data.`)
}

const createManager = async (legacy, now, t) => {
  const [pkg] = await select(
    'SELECT id, duration, role_id FROM packages WHERE name = :name AND deleted_at IS NULL',
    { name: args.package },
    t
  )
  if (!pkg) throw new Error(`Package "${args.package}" not found`)
  if (!pkg.role_id)
    throw new Error(`Package "${args.package}" has no system role`)

  const admin = legacy.users.find((u) => u.id === '1')
  const password = args.password
    ? await bcrypt.hash(args.password, 10)
    : admin.password

  const managerId = await insertOne(
    'users',
    {
      name: args.name,
      username: args.username,
      password,
      user_type: 'manager',
      status: 1,
      parent_id: 1,
      created_at: now,
      updated_at: now,
    },
    t
  )

  const months = Number(args.months)
  await insertOne(
    'subscriptions',
    {
      user_id: managerId,
      package_id: pkg.id,
      valid_from: now,
      valid_to: addMonths(now, months),
      kind: 'initial',
      created_at: now,
      updated_at: now,
    },
    t
  )

  await insertOne(
    'invoice_configs',
    {
      name: args.name,
      number: 0,
      parent_id: managerId,
      created_at: now,
      updated_at: now,
    },
    t
  )

  return managerId
}

const syncStaff = async (legacy, masterId, now, t) => {
  const readPermissions = (
    await select(
      `SELECT p.id, p.key FROM permissions p
       JOIN role_permissions rp ON rp.permission_id = p.id
       JOIN packages pk ON pk.role_id = rp.role_id
       JOIN subscriptions s ON s.package_id = pk.id
       WHERE s.user_id = :masterId AND s.deleted_at IS NULL AND p.key LIKE '%:read'`,
      { masterId },
      t
    )
  ).filter(
    (p) =>
      !STAFF_EXCLUDED_PERMISSION_PREFIXES.some((prefix) =>
        p.key.startsWith(prefix)
      )
  )

  const staff = []
  for (const user of legacy.users.filter((u) => u.id !== '1')) {
    const username = txt(user.username)
    const [existing] = await select(
      'SELECT id, parent_id FROM users WHERE username = :username',
      { username },
      t
    )
    let userId
    if (existing) {
      if (existing.parent_id !== masterId) {
        throw new Error(
          `Username "${username}" is already taken by another account`
        )
      }
      userId = existing.id
      await sequelize.query(
        'DELETE FROM user_permissions WHERE user_id = :userId',
        {
          replacements: { userId },
          transaction: t,
        }
      )
    } else {
      userId = await insertOne(
        'users',
        {
          name: txt(user.name) ?? username,
          username,
          password: user.password,
          phone: txt(user.phone),
          user_type: 'staff',
          status: user.banned === '1' ? 0 : 1,
          parent_id: masterId,
          created_at: legacyTs(user.created) ?? now,
          updated_at: now,
        },
        t
      )
    }

    await insertMany(
      'user_permissions',
      readPermissions.map((p) => ({
        user_id: userId,
        permission_id: p.id,
        created_at: now,
        updated_at: now,
      })),
      t
    )
    staff.push(username)
  }
  return staff
}

const importBusinessData = async (legacy, masterId, now, t) => {
  const counts = {}
  const tenant = (row) => ({ master_id: masterId, ...row })

  // Internal vendor + system items (mirrors authService.createManager)
  const internalVendorId = await insertOne(
    'vendors',
    tenant({
      name: 'Internal',
      vendor_type: 'internal',
      address: 'nil',
      opening_balance: 0,
      status: 'active',
      created_at: now,
      updated_at: now,
    }),
    t
  )
  const [integrationItemId, workingItemId] = await insertMany(
    'items',
    [
      ['Integration Cost', 'integration'],
      ['Working Cost', 'working'],
      ['General', 'general'],
    ].map(([name, type]) =>
      tenant({
        name,
        type,
        vendor_id: internalVendorId,
        base_price: 0,
        status: 'active',
        created_at: now,
        updated_at: now,
      })
    ),
    t
  )

  // Seasons
  const seasonDates = new Map()
  const trackSeasonDate = (seasonId, date) => {
    if (!seasonId || !date) return
    const d = seasonDates.get(seasonId) || { min: date, max: date }
    if (date < d.min) d.min = date
    if (date > d.max) d.max = date
    seasonDates.set(seasonId, d)
  }
  for (const r of legacy.expense) trackSeasonDate(r.season_id, day(r.date))
  for (const r of legacy.sales) trackSeasonDate(r.season_id, day(r.date))
  for (const r of legacy.general_transaction)
    trackSeasonDate(r.season_id, day(r.date))

  const seasonCloseDate = new Map(
    legacy.season_close_report.map((r) => [
      r.season_id,
      closeReportDate(r.date),
    ])
  )
  const seasonRows = legacy.seasons.map((s) => {
    const txnDates = seasonDates.get(s.id)
    const closedOn =
      s.status === '2'
        ? (seasonCloseDate.get(s.id) ?? legacyTs(s.updated_at))
        : null
    const fromDate = day(s.from_date) ?? txnDates?.min ?? day(s.created_at)
    const oneYearOn = addMonths(fromDate, 12)
    let toDate = day(s.to_date) ?? closedOn ?? oneYearOn
    if (txnDates?.max && txnDates.max > toDate) toDate = txnDates.max
    if (toDate <= fromDate) toDate = oneYearOn
    return tenant({
      name: txt(s.name),
      from_date: fromDate,
      to_date: toDate,
      status: s.status === '0' ? 'inactive' : 'active',
      closed_on: closedOn,
      ...stamps(s, now),
    })
  })
  const seasonIds = await insertMany('seasons', seasonRows, t)
  const seasonMap = new Map(legacy.seasons.map((s, i) => [s.id, seasonIds[i]]))
  counts.seasons = seasonIds.length

  // Farms
  const farmIds = await insertMany(
    'farms',
    legacy.farms.map((f) =>
      tenant({
        name: txt(f.name),
        place: txt(f.place),
        capacity: txt(f.capacity),
        own: f.owne === '1',
        status: f.status === '0' ? 'inactive' : 'active',
        ...stamps(f, now),
      })
    ),
    t
  )
  const farmMap = new Map(legacy.farms.map((f, i) => [f.id, farmIds[i]]))
  counts.farms = farmIds.length

  // Batches (close report becomes closing_statement)
  const closeReports = new Map(
    legacy.batch_close_report.map((r) => [r.batch_id, r])
  )
  const batchRows = legacy.batchs.map((b) => {
    const report = closeReports.get(b.id)
    const closedOn =
      b.status === '2'
        ? ((report && closeReportDate(report.date)) ?? legacyTs(b.updated_at))
        : null
    const closingStatement = report
      ? JSON.stringify([
          {
            log:
              `Imported from NPG: avg weight ${report.avg_weight} kg, FCR ${report.fcr}, ` +
              `CFCR ${report.cfcr}, avg cost ${report.avg_cost}/kg, avg rate ${report.avg_rate}/kg, ` +
              `profit ${report.profit}`,
            created_at: closedOn?.toISOString() ?? null,
          },
        ])
      : null
    return tenant({
      name: txt(b.name),
      season_id: seasonMap.get(b.season_id),
      farm_id: farmMap.get(b.farm_id),
      status: b.status === '0' ? 'inactive' : 'active',
      closed_on: closedOn,
      closing_statement: closingStatement,
      ...stamps(b, now),
    })
  })
  const batchIds = await insertMany('batches', batchRows, t)
  const batchMap = new Map(legacy.batchs.map((b, i) => [b.id, batchIds[i]]))
  const batchFarm = new Map(
    legacy.batchs.map((b) => [b.id, farmMap.get(b.farm_id)])
  )
  counts.batches = batchIds.length

  // Vendors (suppliers) and buyers (customers). Legacy balances use the opposite sign.
  // Legacy added "credit" vendor returns to the amount owed while Farmora ignores
  // them, so they are carried in the opening balance to keep the legacy figure.
  const creditReturnsByVendor = new Map()
  for (const r of legacy.purchase_book) {
    if (ref(r.return_id) && r.payment_status === '2') {
      creditReturnsByVendor.set(
        r.vendor_id,
        (creditReturnsByVendor.get(r.vendor_id) ?? 0) + num(r.amount)
      )
    }
  }
  const toVendorRow = (v, vendorType, adjustment = 0) =>
    tenant({
      name: txt(v.name),
      vendor_type: vendorType,
      address: txt(v.address) ?? '-',
      opening_balance: round2(-num(v.opening_balance) + adjustment),
      status: v.status === '1' ? 'active' : 'inactive',
      ...stamps(v, now),
    })
  const suppliers = legacy.vendors.filter((v) => v.status !== '2')
  const buyers = legacy.buyers.filter((b) => b.status !== '2')
  const supplierIds = await insertMany(
    'vendors',
    suppliers.map((v) =>
      toVendorRow(v, 'supplier', creditReturnsByVendor.get(v.id) ?? 0)
    ),
    t
  )
  const buyerIds = await insertMany(
    'vendors',
    buyers.map((b) => toVendorRow(b, 'customer')),
    t
  )
  const vendorMap = new Map(suppliers.map((v, i) => [v.id, supplierIds[i]]))
  const buyerMap = new Map(buyers.map((b, i) => [b.id, buyerIds[i]]))
  counts.suppliers = supplierIds.length
  counts.buyers = buyerIds.length

  // Items: one per (supplier, legacy stock type)
  const itemMap = new Map()
  const itemsByType = new Map()
  const ensureItem = async (legacyVendorId, legacyType) => {
    const def = LEGACY_ITEM_TYPES[legacyType]
    if (!def) throw new Error(`Unknown legacy stock type "${legacyType}"`)
    const vendorId = vendorMap.get(legacyVendorId) ?? internalVendorId
    const key = `${vendorId}:${def.type}`
    if (!itemMap.has(key)) {
      const itemId = await insertOne(
        'items',
        tenant({
          name: def.name,
          type: def.type,
          vendor_id: vendorId,
          base_price: 0,
          status: 'active',
          created_at: now,
          updated_at: now,
        }),
        t
      )
      itemMap.set(key, itemId)
      if (!itemsByType.has(def.type)) itemsByType.set(def.type, itemId)
    }
    return itemMap.get(key)
  }

  // Purchases (legacy "expense")
  const purchaseRows = []
  const batchItem = new Map()
  let maxInvoiceNumber = 0
  for (const e of legacy.expense) {
    const type = txt(e.type)
    const batchId = batchMap.get(e.batch_id)
    if (!batchId) {
      warn(`expense #${e.id} (${type}) has no batch; skipped`)
      continue
    }
    const paid = e.payment_type === '1'
    let categoryId
    let vendorId
    let paymentType = paid ? 'paid' : 'credit'
    if (type === 'Integration Cost') {
      categoryId = integrationItemId
      vendorId = internalVendorId
      paymentType = 'credit'
    } else if (type === 'Working Cost') {
      categoryId = workingItemId
      vendorId = internalVendorId
      paymentType = 'paid'
    } else {
      vendorId = vendorMap.get(e.vendor_id)
      if (!vendorId) {
        warn(
          `expense #${e.id} (${type}) has unknown vendor ${e.vendor_id}; skipped`
        )
        continue
      }
      categoryId = await ensureItem(e.vendor_id, type)
      batchItem.set(`${e.batch_id}:${LEGACY_ITEM_TYPES[type].type}`, categoryId)
    }

    const invoice = txt(e.invoice_number) ?? `NPG/${e.id}`
    const invoiceNo = Number(invoice.replace(/\D/g, ''))
    if (invoiceNo > maxInvoiceNumber) maxInvoiceNumber = invoiceNo

    purchaseRows.push(
      tenant({
        name: type,
        category_id: categoryId,
        quantity: Math.round(num(e.quantity)),
        price_per_unit: num(e.rate),
        total_price: num(e.amount),
        net_amount: num(e.net_amount),
        discount_price: num(e.discount) ? num(e.discount) : null,
        invoice_number: invoice,
        invoice_date: day(e.date),
        vendor_id: vendorId,
        season_id: seasonMap.get(e.season_id),
        batch_id: batchId,
        farm_id: batchFarm.get(e.batch_id),
        payment_type: paymentType,
        narration: txt(e.description),
        status: 'active',
        ...stamps(e, now),
      })
    )
  }
  const purchaseIds = await insertMany('purchases', purchaseRows, t)
  await insertMany(
    'purchase_batch_assignments',
    purchaseIds.map((purchaseId, i) => ({
      purchase_id: purchaseId,
      batch_id: purchaseRows[i].batch_id,
      quantity: 0,
      created_at: now,
      updated_at: now,
    })),
    t
  )
  counts.purchases = purchaseIds.length

  // Integration book: farm payments, plus the paid half of paid integration costs
  const integrationRows = legacy.integration_book
    .filter((r) => r.register_id === '0' || r.payment_status === '1')
    .map((r) =>
      tenant({
        farm_id: farmMap.get(r.farm_id),
        date: day(r.date),
        amount: num(r.amount),
        payment_type: 'paid',
        status: 'active',
        ...stamps(r, now),
      })
    )
  counts.integration_books = (
    await insertMany('integration_books', integrationRows, t)
  ).length

  // Working cost book: manual entries only (batch charges are working-cost purchases)
  const workingRows = legacy.workingcost_book
    .filter((r) => r.register_id === '0')
    .map((r) =>
      tenant({
        season_id: seasonMap.get(r.season_id),
        date: day(r.date),
        purpose: txt(r.purpose) ?? 'Working cost',
        amount: num(r.amount),
        payment_type: r.payment_status === '1' ? 'income' : 'expense',
        status: 'active',
        ...stamps(r, now),
      })
    )
  counts.working_costs = (
    await insertMany('working_costs', workingRows, t)
  ).length

  // Rental farm, salary and egg setting cash entries (modules Farmora lacks),
  // taken from the legacy balance sheet and filed under the season of their date
  const seasonsByStart = seasonRows
    .map((s, i) => ({ id: seasonIds[i], from: s.from_date }))
    .sort((a, b) => a.from - b.from)
  const seasonForDate = (date) =>
    seasonsByStart.findLast((s) => s.from <= date)?.id ?? seasonsByStart[0].id
  const businessPlusRows = (legacy.business_plus_cash ?? []).map((r) => {
    const date = day(r.date)
    return tenant({
      season_id: seasonForDate(date),
      date,
      purpose: `${BUSINESS_PLUS_LABELS[r.type]} - ${txt(r.purpose) ?? 'Entry'}`,
      amount: num(r.amount),
      payment_type: r.transaction === 'In' ? 'income' : 'expense',
      status: 'active',
      ...stamps(r, now),
    })
  })
  counts.business_plus_cash = (
    await insertMany('working_costs', businessPlusRows, t)
  ).length

  // Purchase book: vendor payments (bill rows are represented by purchases)
  const returnPayment = new Map()
  const vendorPayments = []
  for (const r of legacy.purchase_book) {
    if (ref(r.return_id)) {
      returnPayment.set(
        r.return_id,
        r.payment_status === '1' ? 'paid' : 'credit'
      )
    } else if (r.register_id === '0') {
      if (r.payment_status !== '1') {
        warn(`purchase_book #${r.id} is a manual credit entry; skipped`)
        continue
      }
      const vendorId = vendorMap.get(r.vendor_id)
      if (!vendorId) {
        warn(
          `purchase_book #${r.id} has unknown vendor ${r.vendor_id}; skipped`
        )
        continue
      }
      vendorPayments.push(
        tenant({
          vendor_id: vendorId,
          amount: num(r.amount),
          date: day(r.date),
          ...stamps(r, now),
        })
      )
    }
  }
  counts.purchase_books = (
    await insertMany('purchase_books', vendorPayments, t)
  ).length

  // Returns and batch-to-batch transfers
  const returnRows = []
  for (const r of legacy.stock_return_issue) {
    const def = LEGACY_ITEM_TYPES[txt(r.type)]
    const toVendor = r.return_to === 'Vendor'
    let categoryId
    if (toVendor) {
      categoryId = await ensureItem(r.to_vendor_id, txt(r.type))
    } else {
      categoryId =
        batchItem.get(`${r.from_batch_id}:${def.type}`) ??
        itemsByType.get(def.type)
      if (!categoryId) categoryId = await ensureItem(null, txt(r.type))
    }
    returnRows.push(
      tenant({
        return_type: toVendor ? 'vendor' : 'batch',
        item_category_id: categoryId,
        date: day(r.entry_date),
        from_batch: batchMap.get(r.from_batch_id),
        to_batch: toVendor ? null : batchMap.get(r.to_batch_id),
        to_vendor: toVendor ? vendorMap.get(r.to_vendor_id) : null,
        quantity: Math.round(num(r.quantity)),
        rate_per_bag: num(r.rate),
        total_amount: num(r.net_rate),
        status: 'completed',
        payment_type: toVendor ? (returnPayment.get(r.id) ?? 'paid') : 'credit',
        ...stamps(r, now),
      })
    )
  }
  counts.purchase_returns = (
    await insertMany('purchase_returns', returnRows, t)
  ).length

  // Sales, plus buyer payments from the legacy sales book
  const cashSales = new Set(
    legacy.sales_book
      .filter((r) => ref(r.sales_id) && r.payment_status === '1')
      .map((r) => r.sales_id)
  )
  const salesRows = legacy.sales.map((s) => {
    const weight = num(s.weight)
    const birds = Math.round(num(s.bird_no))
    return tenant({
      season_id: seasonMap.get(s.season_id),
      batch_id: batchMap.get(s.batch_id),
      date: day(s.date),
      buyer_id: buyerMap.get(s.buyer_id),
      vehicle_no: txt(s.vehicle_no),
      weight,
      bird_no: birds,
      avg_weight: birds ? Math.round((weight / birds) * 10000) / 10000 : null,
      price: num(s.price),
      amount: num(s.amount),
      payment_type: cashSales.has(s.id) ? 'cash' : 'credit',
      narration: txt(s.description),
      status: 'active',
      ...stamps(s, now),
    })
  })
  const buyerPayments = legacy.sales_book
    .filter((r) => !ref(r.sales_id))
    .map((r) =>
      tenant({
        date: day(r.date),
        buyer_id: buyerMap.get(r.buyer_id),
        amount: num(r.amount),
        payment_type: 'paid',
        status: 'active',
        ...stamps(r, now),
      })
    )
  counts.sales = (await insertMany('sales', salesRows, t)).length
  counts.buyer_payments = (await insertMany('sales', buyerPayments, t)).length

  // General expenses (Out) and general sales (In)
  const toGeneralRow = (g) =>
    tenant({
      season_id: seasonMap.get(g.season_id),
      purpose: txt(g.purpose) ?? 'General',
      date: day(g.date),
      amount: num(g.total_rate),
      narration: txt(g.description),
      status: 'active',
      ...stamps(g, now),
    })
  counts.general_expenses = (
    await insertMany(
      'general_expenses',
      legacy.general_transaction
        .filter((g) => g.transaction === 'Out')
        .map(toGeneralRow),
      t
    )
  ).length
  counts.general_sales = (
    await insertMany(
      'expense_sales',
      legacy.general_transaction
        .filter((g) => g.transaction === 'In')
        .map(toGeneralRow),
      t
    )
  ).length

  // Investors: capital from active investments, profit shares from season close
  const investorIds = await insertMany(
    'investor_managements',
    legacy.invester.map((inv) =>
      tenant({
        investor_name: txt(inv.name),
        investor_phone: txt(inv.phone),
        investor_email: txt(inv.email),
        is_active: inv.status === '1',
        ...stamps(inv, now),
      })
    ),
    t
  )
  const investorMap = new Map(
    legacy.invester.map((inv, i) => [inv.id, investorIds[i]])
  )
  const txnTypes = new Map(
    (
      await select('SELECT id, code FROM investor_transaction_types', {}, t)
    ).map((r) => [r.code, r.id])
  )
  // Legacy investment "amount" is an ownership percentage, not money, so it is
  // recorded on the profit credits instead of as capital.
  const ownershipShare = new Map(
    legacy.investment
      .filter((inv) => inv.status === '1')
      .map((inv) => [`${inv.invester_id}:${inv.season_id}`, num(inv.amount)])
  )
  const investorTxns = legacy.invester_season_profit
    .filter((p) => ref(p.invester_id))
    .map((p) => {
      const closed = seasonCloseDate.get(p.season_id) ?? legacyTs(p.created_at)
      const share = ownershipShare.get(`${p.invester_id}:${p.season_id}`)
      return tenant({
        investor_id: investorMap.get(p.invester_id),
        transaction_type_id: txnTypes.get('PROFIT_CREDIT'),
        amount: num(p.share_amount),
        transaction_date: closed.toISOString().slice(0, 10),
        season_id: seasonMap.get(p.season_id),
        remarks:
          `Imported from NPG season profit share #${p.id}` +
          (share ? ` (${share}% ownership)` : ''),
        ...stamps(p, now),
      })
    })
  counts.investors = investorIds.length
  counts.investor_transactions = (
    await insertMany('investor_transactions', investorTxns, t)
  ).length

  await sequelize.query(
    'UPDATE invoice_configs SET number = GREATEST(number, :n), updated_at = :now WHERE parent_id = :masterId',
    { replacements: { n: maxInvoiceNumber, now, masterId }, transaction: t }
  )

  return { counts, batchMap, seasonMap, vendorMap, buyerMap }
}

const verify = async (legacy, masterId, maps) => {
  const replacements = { masterId }
  const byId = (rows, key = 'id') =>
    new Map(rows.map((r) => [r[key], Number(r.v)]))

  const salesByBatch = byId(
    await select(
      `SELECT batch_id AS id, SUM(amount) AS v FROM sales
       WHERE master_id = :masterId AND season_id IS NOT NULL GROUP BY batch_id`,
      replacements
    )
  )
  const purchasesByBatch = byId(
    await select(
      'SELECT batch_id AS id, SUM(net_amount) AS v FROM purchases WHERE master_id = :masterId GROUP BY batch_id',
      replacements
    )
  )
  const transfersIn = byId(
    await select(
      'SELECT to_batch AS id, SUM(total_amount) AS v FROM purchase_returns WHERE master_id = :masterId GROUP BY to_batch',
      replacements
    )
  )
  const returnsOut = byId(
    await select(
      'SELECT from_batch AS id, SUM(total_amount) AS v FROM purchase_returns WHERE master_id = :masterId GROUP BY from_batch',
      replacements
    )
  )
  const batchProfit = (batchId) =>
    (salesByBatch.get(batchId) ?? 0) -
    ((purchasesByBatch.get(batchId) ?? 0) +
      (transfersIn.get(batchId) ?? 0) -
      (returnsOut.get(batchId) ?? 0))

  const batchMismatches = legacy.batch_close_report
    .map((r) => ({
      batch: r.batch_id,
      legacy: num(r.profit),
      farmora: round2(batchProfit(maps.batchMap.get(r.batch_id))),
    }))
    .filter((r) => Math.abs(r.legacy - r.farmora) > 1)

  const generalBySeason = byId(
    await select(
      'SELECT season_id AS id, SUM(amount) AS v FROM general_expenses WHERE master_id = :masterId GROUP BY season_id',
      replacements
    )
  )
  const generalSalesBySeason = byId(
    await select(
      'SELECT season_id AS id, SUM(amount) AS v FROM expense_sales WHERE master_id = :masterId GROUP BY season_id',
      replacements
    )
  )
  const seasonChecks = legacy.season_close_report.map((r) => {
    const seasonId = maps.seasonMap.get(r.season_id)
    const batchTotal = legacy.batchs
      .filter((b) => b.season_id === r.season_id)
      .reduce((sum, b) => sum + batchProfit(maps.batchMap.get(b.id)), 0)
    return {
      season: r.season_id,
      legacy: num(r.season_profit),
      farmora: round2(
        batchTotal -
          (generalBySeason.get(seasonId) ?? 0) +
          (generalSalesBySeason.get(seasonId) ?? 0)
      ),
    }
  })

  const supplierBalances = byId(
    await select(
      `SELECT v.id, v.opening_balance
         + COALESCE((SELECT SUM(total_price) FROM purchases p WHERE p.vendor_id = v.id AND p.payment_type = 'credit'), 0)
         - COALESCE((SELECT SUM(amount) FROM purchase_books b WHERE b.vendor_id = v.id), 0)
         - COALESCE((SELECT SUM(total_amount) FROM purchase_returns r WHERE r.to_vendor = v.id AND r.payment_type = 'paid'), 0) AS v
       FROM vendors v WHERE v.master_id = :masterId AND v.vendor_type = 'supplier'`,
      replacements
    )
  )
  const supplierMismatches = legacy.vendors
    .filter((v) => maps.vendorMap.has(v.id))
    .map((v) => {
      const rows = legacy.purchase_book.filter((r) => r.vendor_id === v.id)
      const paid = rows
        .filter((r) => r.payment_status === '1')
        .reduce((s, r) => s + num(r.amount), 0)
      const credit = rows
        .filter((r) => r.payment_status === '2')
        .reduce((s, r) => s + num(r.amount), 0)
      return {
        vendor: txt(v.name),
        legacyOwed: round2(credit - paid - num(v.opening_balance)),
        farmoraOwed: round2(supplierBalances.get(maps.vendorMap.get(v.id))),
      }
    })
    .filter((r) => Math.abs(r.legacyOwed - r.farmoraOwed) > 1)

  const buyerBalances = byId(
    await select(
      `SELECT v.id, v.opening_balance
         + COALESCE((SELECT SUM(amount) FROM sales s WHERE s.buyer_id = v.id AND s.payment_type = 'credit'), 0)
         - COALESCE((SELECT SUM(amount) FROM sales s WHERE s.buyer_id = v.id AND s.payment_type = 'paid'), 0) AS v
       FROM vendors v WHERE v.master_id = :masterId AND v.vendor_type = 'customer'`,
      replacements
    )
  )
  const buyerMismatches = legacy.buyers
    .filter((b) => maps.buyerMap.has(b.id))
    .map((b) => {
      const rows = legacy.sales_book.filter((r) => r.buyer_id === b.id)
      const paid = rows
        .filter((r) => r.payment_status === '1')
        .reduce((s, r) => s + num(r.amount), 0)
      const credit = rows
        .filter((r) => r.payment_status === '2')
        .reduce((s, r) => s + num(r.amount), 0)
      return {
        buyer: txt(b.name),
        legacyDue: round2(credit - paid - num(b.opening_balance)),
        farmoraDue: round2(buyerBalances.get(maps.buyerMap.get(b.id))),
      }
    })
    .filter((r) => Math.abs(r.legacyDue - r.farmoraDue) > 1)

  console.log('\nVerification against legacy reports')
  console.log(
    `  Batch profit: ${legacy.batch_close_report.length - batchMismatches.length}/${legacy.batch_close_report.length} closed batches match`
  )
  if (batchMismatches.length) console.table(batchMismatches)
  console.log('  Season profit:')
  console.table(seasonChecks)
  console.log(
    `  Supplier balances: ${supplierMismatches.length ? 'differences below' : 'all match'}`
  )
  if (supplierMismatches.length) console.table(supplierMismatches)
  console.log(
    `  Buyer balances: ${buyerMismatches.length ? 'differences below' : 'all match'}`
  )
  if (buyerMismatches.length) console.table(buyerMismatches)
}

const runImport = async () => {
  const legacy = loadLegacyData(args.data)
  console.log(`Using ${args.data} (exported ${legacy.exported_at})`)
  const now = new Date()

  const result = await sequelize.transaction(async (t) => {
    const existing = await findManager(t)
    let masterId
    if (existing) {
      if (!args.replace) {
        throw new Error(
          `Manager "${args.username}" already exists. Use --replace to re-import or --remove to delete it.`
        )
      }
      masterId = existing.id
      await wipeTenantData(masterId, t)
    } else {
      masterId = await createManager(legacy, now, t)
    }

    const staff = await syncStaff(legacy, masterId, now, t)
    const data = await importBusinessData(legacy, masterId, now, t)
    return { masterId, staff, ...data }
  })

  console.log(
    `Imported NPG into manager "${args.username}" (id ${result.masterId})`
  )
  console.log(`Staff logins (read-only): ${result.staff.join(', ')}`)
  console.table(result.counts)
  if (warnings.length) {
    console.log('Warnings:')
    for (const w of warnings) console.log(`  - ${w}`)
  }

  await verify(legacy, result.masterId, result)
}

try {
  await (args.remove ? removeTenant() : runImport())
} catch (error) {
  console.error(`Import failed: ${error.message}`)
  process.exitCode = 1
} finally {
  await sequelize.close()
}
