/**
 * Generates src/theme/tokens.css from src/theme/tokens.ts.
 *
 * This is the build-time step that converts the design tokens (single source of
 * truth) into real CSS custom properties, so Tailwind utilities and any plain
 * CSS can consume them. Run via `bun run gen:tokens` (hooked into dev/build).
 *
 *   :root                → static tokens + light semantic roles
 *   [data-theme="dark"]  → dark semantic roles (flips on data-theme toggle)
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { toModeCssVars, toStaticCssVars } from '../src/theme/tokens'

const here = dirname(fileURLToPath(import.meta.url))
const outFile = resolve(here, '../src/theme/tokens.css')

const serialize = (vars: Record<string, string>, indent: string) =>
  Object.entries(vars)
    .map(([key, value]) => `${indent}${key}: ${value};`)
    .join('\n')

const css = `/* AUTO-GENERATED by scripts/gen-tokens.ts — DO NOT EDIT.
   Source of truth: src/theme/tokens.ts */
:root {
${serialize({ ...toStaticCssVars(), ...toModeCssVars('light') }, '  ')}
}

[data-theme="dark"] {
${serialize(toModeCssVars('dark'), '  ')}
}
`

mkdirSync(dirname(outFile), { recursive: true })
writeFileSync(outFile, css, 'utf8')
console.log(`✓ Wrote ${outFile}`)
