import {
  ArrowLeftRight,
  BarChart3,
  Banknote,
  BookOpenCheck,
  BookText,
  Boxes,
  CalendarDays,
  CalendarRange,
  CircleDollarSign,
  ClipboardList,
  Coins,
  CreditCard,
  Gift,
  Layers,
  LayoutDashboard,
  NotebookTabs,
  Package,
  PiggyBank,
  Receipt,
  Settings,
  Shield,
  ShoppingCart,
  Tag,
  Tractor,
  TrendingUp,
  Truck,
  Undo2,
  UserRound,
  Users,
  Wallet,
} from "lucide-react";
import type { Paths } from "./types/paths.types";

export const paths: Paths = [
  {
    pathname: "Dashboard",
    link: "/dashboard",
    icon: LayoutDashboard,
    audience: "tenant",
    permission: "dashboard:read",
  },
  {
    pathname: "Dashboard",
    link: "/dashboard",
    icon: LayoutDashboard,
    audience: "platform",
  },
  {
    pathname: "Subscribers",
    link: "/subscribers",
    icon: Users,
    audience: "platform",
    permission: "subscriber:read",
  },
  {
    pathname: "Packages",
    link: "/packages",
    icon: CreditCard,
    audience: "platform",
    permission: "package:read",
  },
  {
    pathname: "Subscriptions",
    link: "/subscriptions",
    icon: Package,
    audience: "platform",
    permission: "subscription:read",
  },
  {
    pathname: "Referrals",
    link: "/referrals",
    icon: Gift,
    audience: "platform",
    permission: "referral:read",
  },
  {
    pathname: "Expense",
    icon: Wallet,
    audience: "tenant",
    children: [
      {
        pathname: "Purchase",
        link: "/expense/purchase",
        icon: ShoppingCart,
        permission: "purchase:read",
        audience: "tenant",
      },
      {
        pathname: "Returns",
        link: "/expense/returns",
        icon: Undo2,
        permission: "item_return:read",
        audience: "tenant",
      },
      {
        pathname: "Purchase Book",
        link: "/expense/purchase-book",
        icon: BookText,
        permission: "purchase_book:read",
        audience: "tenant",
      },
      {
        pathname: "Integration Book",
        link: "/expense/integration-book",
        icon: NotebookTabs,
        permission: "integration_book:read",
        audience: "tenant",
      },
      {
        pathname: "Working Cost Book",
        link: "/expense/working-cost-book",
        icon: ClipboardList,
        permission: "working_cost:read",
        audience: "tenant",
      },
    ],
  },
  {
    pathname: "Sales",
    icon: TrendingUp,
    audience: "tenant",
    children: [
      {
        pathname: "Sale",
        link: "/sales/sale",
        icon: Tag,
        permission: "sale:read",
        audience: "tenant",
      },
      {
        pathname: "Sales Book",
        link: "/sales/sales-book",
        icon: BookOpenCheck,
        permission: "sales_book:read",
        audience: "tenant",
      },
    ],
  },
  {
    pathname: "General",
    icon: Layers,
    audience: "tenant",
    children: [
      {
        pathname: "General Expense",
        link: "/general/general-expense",
        icon: Receipt,
        permission: "general_expense:read",
        audience: "tenant",
      },
      {
        pathname: "General Sales",
        link: "/general/general-sales",
        icon: Coins,
        permission: "general_sales:read",
        audience: "tenant",
      },
    ],
  },
  {
    pathname: "Cash Flow",
    link: "/cash-flow",
    icon: ArrowLeftRight,
    audience: "tenant",
    permission: "cash_flow:read",
  },
  {
    pathname: "Overview",
    icon: BarChart3,
    audience: "tenant",
    children: [
      {
        pathname: "Season Overview",
        link: "/overview/season",
        icon: CalendarDays,
        permission: "season_overview:read",
        audience: "tenant",
      },
      {
        pathname: "Batch Overview",
        link: "/overview/batch",
        icon: Boxes,
        permission: "batch_overview:read",
        audience: "tenant",
      },
    ],
  },
  {
    pathname: "Invest",
    icon: PiggyBank,
    audience: "tenant",
    children: [
      {
        pathname: "Management",
        link: "/investors/management",
        icon: Users,
        permission: "investor:read",
        audience: "tenant",
      },
      {
        pathname: "Investments",
        link: "/investors/ledger/invest",
        icon: Banknote,
        permission: "investor_ledger:read",
        audience: "tenant",
      },
      {
        pathname: "Profits",
        link: "/investors/ledger/profit",
        icon: CircleDollarSign,
        permission: "investor_ledger:read",
        audience: "tenant",
      },
    ],
  },
  {
    pathname: "Configuration",
    icon: Settings,
    audience: "tenant",
    children: [
      {
        pathname: "Items",
        link: "/configuration/items",
        icon: Package,
        permission: "item:read",
        audience: "tenant",
      },
      {
        pathname: "Farms",
        link: "/configuration/farms",
        icon: Tractor,
        permission: "farm:read",
        audience: "tenant",
      },
      {
        pathname: "Seasons",
        link: "/configuration/seasons",
        icon: CalendarRange,
        permission: "season:read",
        audience: "tenant",
      },
      {
        pathname: "Batches",
        link: "/configuration/batches",
        icon: Boxes,
        permission: "batch:read",
        audience: "tenant",
      },
      {
        pathname: "Vendors",
        link: "/configuration/vendors",
        icon: Truck,
        permission: "vendor:read",
        audience: "tenant",
      },
      {
        pathname: "Users",
        link: "/configuration/users",
        icon: UserRound,
        permission: "user:read",
        audience: "tenant",
      },
      {
        pathname: "Roles",
        link: "/configuration/roles",
        icon: Shield,
        permission: "role:read",
        audience: "tenant",
      },
    ],
  },
];
